version: '3'
services:
  draft-back:
    image: "parsesignal/draft:back_02.000.000"
    container_name: draft-back
    ports:
      - 9000:9000

  draft-ui:
    image: "parsesignal/draft:ui_02.000.000"
    container_name: draft-ui
    ports:
      - 80:80
    links:
      - draft-back